args:
    seed: 636
    env_name: hopper-medium-v2
    num_models: 10
    ensemble: True
    #train_mode: True
    #test_mode: True
    load_model_dir: "./model_saved_weights/Model_seed631_2024_06_22_21-25-13_state_reward_single_step_TrueEnsemble"
    rand_eva: False
    arch_num: 2
    eval_mode : 'multistep'
    plot_trans_pred: True
    #hyper_tune: True
    feature_transform: True # !!!False is NOT YET PREPARED FOR REWARD HEAD
    #rand_val_eval: True
    # MULTI-STEP MODELS ARE NOT YET PREPARED FOR REWARD HEAD
    #multi_step_model: True # should be False when eval without MHN and data pickle will be loaded
    seq_len: 70 # important when making sequence data for the first time
    conformal_hopfield: True # should be False when eval without MHN and data pickle will be loaded
    load_mhn: True
    load_nstep_mhn: True
    trans_model: single_step # MULTI-STEP MODELS ARE NOT YET PREPARED FOR REWARD HEAD
    reward_head: True
    # trans model hyperparameters
    num_layers: 3
    num_nodes: 1024
    model_lr: 0.00007 # lr = 0.00007 Multistep
    model_epochs: 150 # 300 Multi-step
    l2_reg: 0.000001
    horizon: 120
    batch_size: 256 # 256 Multi-step
    # MHN hyperparams
    mhn_epochs: 256 #257 # 255 has 5 trained models stopped at training MHN 6
    mhn_lr: 0.001
    mhn_l2_reg: 0.001
    mhn_batch_size: 128
    num_heads: 1
    # n-step MHN hyperparams
    nstep_mhn_epochs: 300 # 255 has 5 trained models stopped at training MHN 6
    nstep_mhn_lr: 0.0001
    nstep_mhn_l2_reg: 0.001
    nstep_mhn_batch_size: 128
    # n-step calibration options
    nstep_cp_sampling: ['sampling', 120]
    nstep_cp_alphas: 5
    nstep_cp_replacement: True
    # calibration options
    mhn_output: 'y' # delta may not work reward_head
    which_ctxt: 'time' # y_pred may not work reward_head
    calib_horizon: 150 # prepare_hopfield_data skips episodes lower than this to avoid padding for MHN batch training so choose carefully
    cp_sampling: ['sampling', 1000] # For 'sampling' pass no of samples from dist. and for 'topk' pass no of top k probs. you want to pick
    cp_aggregate: 'long_seq'
    cp_alphas: 12 # 9
    cp_replacement: True # Not important for topk
    # autoregresson options
    quant_part_assign: 'det'
    #noise_scale: 0.40
    # behavioral cloning model options
    train_BC_n_step: True # if True, conformal_hopfield=True and load_MHN=False [set to True if you want to use return and BC model]
    bc_batch_size: 256
    bc_lr: 0.0001
    bc_l2_reg: 0.000001
    bc_epochs: 100
    load_bc_nstep: True
    use_bc: True
    mppi_horizon: 4

#"./hopper-medium-v2/multi_step/model_saved_weights/Model_seed614_2024_04_02_10-05-18_7layers_7e-5lr_30Epoch_1e-6l2_256"
#"./hopper-medium-v2/multi_step/model_saved_weights/Model_seed614_2024_04_03_14-48-07_7layers_7e-5lr_40Epoch_1e-6l2_256_5Seq"
#(For MHN)"./hopper-medium-v2/single_step/model_saved_weights/Model_seed614_2024_03_22_21-16-43_new_mod_high_noise_train_best"
#"./hopper-medium-v2/multi_step/model_saved_weights/Model_seed614_2024_04_04_11-55-39_nohup_10layers_50Seq_fulldata"
#"./hopper-medium-v2/multi_step/model_saved_weights/Model_seed614_2024_04_04_16-36-58_nohup_7layers_50Seq_fulldata"
#"./hopper-medium-v2/multi_step/model_saved_weights/Model_seed614_2024_04_08_21-47-01_nohup_7layers_50Seq_0.02Exp"
#(For MHN)"./hopper-medium-v2/multi_step/model_saved_weights/Model_seed614_2024_04_09_13-56-23_nohup_7layers_50Seq_VarNormLoss"
#"./hopper-medium-v2/multi_step/model_saved_weights/Model_seed614_2024_04_11_15-05-39_nohup_7layers_30Seq_VarNorm"
#"./hopper-medium-v2/multi_step/model_saved_weights/Model_seed614_2024_04_11_18-30-35_nohup_7layers_10Seq_VarNorm"
#"./hopper-medium-v2/multi_step/model_saved_weights/Model_seed614_2024_04_09_14-01-53_new_mod_high_noise_train_0.1Exp"
#"./hopper-medium-v2/single_step/model_saved_weights/Model_seed614_2024_04_11_23-51-53_new_mod_high_noise_train_1Seq_VarNorm"
# (For MHN Reward) Model_seed614_2024_05_30_21-57-51_state_reward_single_step (Add FalseEnsemble)
# (For Ensembles) "./model_saved_weights/Model_seed631_2024_06_22_21-25-13_state_reward_single_step_TrueEnsemble"