name: HopCast
channels:
  - pytorch
  - plotly
  - menpo
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.0.5
  - attrs=22.1.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.01.10
  - cffi=1.15.1
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - conda=23.1.0
  - conda-build=3.23.3
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - cryptography=39.0.1
  - cuda=11.6.2
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.6.55
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.6.124
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=11.8.86
  - cuda-libraries=11.6.2
  - cuda-libraries-dev=11.6.2
  - cuda-memcheck=11.8.86
  - cuda-nsight=11.8.86
  - cuda-nsight-compute=11.8.0
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=11.8.86
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=11.8.87
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.6.124
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.6.124
  - cuda-nvvp=11.8.87
  - cuda-runtime=11.6.2
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=11.8.86
  - cuda-toolkit=11.6.2
  - cuda-tools=11.6.2
  - cuda-visual-tools=11.6.2
  - cudatoolkit=11.3.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - elfutils=0.188
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.5.0
  - ffmpeg=4.2.2
  - fftw=3.3.9
  - filelock=3.9.0
  - freetype=2.12.1
  - gds-tools=1.4.0.31
  - gflags=2.2.2
  - giflib=5.2.1
  - glew=2.1.0
  - glfw3=3.2.1
  - glob2=0.7
  - gmp=6.2.1
  - gnutls=3.6.15
  - icu=58.2
  - idna=3.4
  - importlib_resources=5.2.0
  - intel-openmp=2021.4.0
  - ipykernel=6.9.1
  - ipython=8.12.0
  - ipywidgets=8.0.2
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=7.4.9
  - jupyter_core=5.3.0
  - jupyterlab_widgets=3.0.5
  - krb5=1.19.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libarchive=3.5.2
  - libblas=3.9.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcufile=1.4.0.31
  - libcufile-dev=1.4.0.31
  - libcurand=10.3.0.86
  - libcurand-dev=10.3.0.86
  - libcurl=7.88.1
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libdrm=2.4.114
  - libdrm-cos6-x86_64=2.4.65
  - libedit=3.1.20221030
  - libev=4.33
  - libfaiss=1.7.1
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglu=9.0.0
  - libidn2=2.3.2
  - liblapack=3.9.0
  - liblief=0.12.3
  - libmicrohttpd=0.9.75
  - libnghttp2=1.46.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libopus=1.3.1
  - libpciaccess=0.17
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuv=1.44.2
  - libvpx=1.7.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libx11-common-cos6-x86_64=1.6.4
  - libx11-cos6-x86_64=1.6.4
  - libxcb=1.13
  - libxml2=2.9.14
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mesa-libgl-cos6-x86_64=11.0.7
  - mesalib=23.0.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - nsight-compute=2022.3.0.22
  - numexpr=2.8.4
  - openh264=2.1.1
  - openssl=1.1.1u
  - osmesa=12.2.2.dev
  - pandas=1.5.3
  - parso=0.8.3
  - patch=2.7.6
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pkginfo=1.9.6
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.5.2
  - plotly=5.15.0
  - pluggy=1.0.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-lief=0.12.3
  - pycosat=0.6.4
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=23.0.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.15
  - python-dateutil=2.8.2
  - python-devtools=0.11.0
  - python-fastjsonschema=2.16.2
  - python-libarchive-c=2.9
  - python_abi=3.8
  - pytorch-cuda=11.6
  - pytorch-mutex=1.0
  - pytz=2022.7
  - pyyaml=6.0
  - pyzmq=23.2.0
  - readline=8.2
  - requests=2.28.1
  - ripgrep=13.0.0
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - screen=4.8.0
  - setuptools=66.0.0
  - six=1.16.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tabulate=0.8.10
  - tenacity=8.2.2
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - torchaudio=0.11.0
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - tsnecuda=3.0.1
  - typing_extensions=4.5.0
  - urllib3=1.26.15
  - wcwidth=0.2.5
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - x264=1!157.20191217
  - xorg-damageproto=1.2.1
  - xorg-fixesproto=5.0
  - xorg-glproto=1.4.17
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.4
  - xorg-libxcursor=1.2.0
  - xorg-libxdamage=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.2
  - xorg-libxrender=0.9.10
  - xorg-randrproto=1.5.0
  - xorg-renderproto=0.11.1
  - xorg-util-macros=1.19.0
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xz=5.2.10
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
  - pip:
      - absl-py==1.4.0
      - adagio==0.2.4
      - aiohttp==3.9.3
      - aiohttp-cors==0.7.0
      - aiorwlock==1.4.0
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - astropy==5.2.2
      - astroquery==0.4.7
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - backports-tarfile==1.2.0
      - bayesian-optimization==1.4.3
      - blessed==1.20.0
      - bokeh==3.1.1
      - botorch==0.8.5
      - cachetools==4.2.4
      - certifi==2022.12.7
      - click==8.1.3
      - cloudpickle==1.3.0
      - cma==3.3.0
      - cmake==3.27.0
      - colorful==0.5.6
      - comet-ml==3.33.11
      - configobj==5.0.8
      - contourpy==1.0.6
      - copulae==0.7.9
      - coreforecast==0.0.8
      - cvxopt==1.3.2
      - cycler==0.11.0
      - cython==0.29.32
      - darts==0.28.0
      - derivative==0.6.0
      - dm-control==1.0.10
      - dm-env==1.6
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - docstring-parser==0.15
      - docutils==0.19
      - dotmap==1.3.30
      - dulwich==0.21.6
      - einops==0.7.0
      - essentials==1.1.5
      - everett==3.1.0
      - fasteners==0.15
      - flatbuffers==23.5.26
      - fonttools==4.38.0
      - frozenlist==1.4.1
      - fs==2.4.16
      - fsspec==2024.2.0
      - fugue==0.8.7
      - fugue-sql-antlr==0.2.0
      - future==0.18.3
      - gast==0.3.3
      - glfw==1.12.0
      - google-api-core==2.17.1
      - google-auth==1.35.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - googleapis-common-protos==1.62.0
      - gpustat==1.1.1
      - gpy==1.10.0
      - gpytorch==1.10
      - grpcio==1.59.0
      - gym==0.17.0
      - gym-notices==0.0.8
      - h11==0.14.0
      - h5py==2.10.0
      - holidays==0.46
      - html5lib==1.1
      - httptools==0.6.1
      - hydra==2.5
      - hydra-core==1.2.0
      - imagehash==4.3.1
      - imageio==2.26.0
      - importlib-metadata==6.6.0
      - ipdb==0.13.13
      - jaraco-classes==3.4.0
      - jaraco-context==5.3.0
      - jaraco-functools==4.0.1
      - jeepney==0.8.0
      - joblib==1.2.0
      - jplephem==2.22
      - kaleido==0.2.1
      - keras==2.13.1
      - keras-preprocessing==1.1.2
      - keyring==25.2.1
      - kiwisolver==1.4.4
      - labmaze==1.0.6
      - libclang==16.0.6
      - lightgbm==3.3.3
      - lightning-utilities==0.11.2
      - linear-operator==0.4.0
      - lit==16.0.6
      - llvmlite==0.41.1
      - lxml==4.9.2
      - markdown==3.4.4
      - matplotlib==3.6.2
      - memory-profiler==0.61.0
      - mjrl==1.0.0
      - monotonic==1.6
      - more-itertools==10.3.0
      - mpmath==1.3.0
      - msgpack==1.0.8
      - mujoco-py==2.1.2.14
      - multidict==6.0.5
      - multipledispatch==1.0.0
      - networkx==3.1
      - neuralhydrology==1.10.0
      - nevergrad==0.11.0
      - nfoursid==1.0.1
      - numba==0.58.1
      - numpy==1.22.0
      - numpydoc==1.5.0
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.2.5.6
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.2.140
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.2.140
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.4.25
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-ml-py==12.535.133
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-tensorrt==99.0.0
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opt-einsum==3.3.0
      - packaging==21.3
      - paramz==0.9.5
      - patchelf==0.17.2.1
      - patsy==0.5.3
      - pip==24.2
      - pmdarima==2.0.4
      - poliastro==0.17.0
      - prometheus-client==0.20.0
      - protobuf==3.20.1
      - py-spy==0.3.14
      - pyaml==21.10.1
      - pyarrow==15.0.1
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pybullet==3.2.5
      - pyerfa==2.0.0.3
      - pygame==2.5.2
      - pyglet==1.5.0
      - pyod==1.1.3
      - pyopengl==3.1.6
      - pyparsing==3.0.9
      - pyro-api==0.1.2
      - pyro-ppl==1.8.6
      - pysindy==1.7.5
      - pytest-instafail==0.3.0
      - python-box==6.1.0
      - python-dotenv==1.0.1
      - pytorch-lightning==2.1.4
      - pytorch-tabnet==4.1.0
      - pytorch-tabular==1.1.0
      - pyvo==1.5.2
      - pywavelets==1.4.1
      - qpd==0.4.4
      - ray==2.9.3
      - requests-oauthlib==1.3.1
      - requests-toolbelt==1.0.0
      - rsa==4.9
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - scs==3.2.7
      - seaborn==0.13.2
      - secretstorage==3.3.3
      - semantic-version==2.10.0
      - sentry-sdk==1.31.0
      - setproctitle==1.3.3
      - sgp4==2.23
      - shap==0.44.1
      - simplejson==3.19.1
      - sk-video==1.1.10
      - slicer==0.0.7
      - smart-open==7.0.1
      - sphinx-rtd-theme==1.2.0
      - sphinxcontrib-jquery==4.1
      - sqlglot==22.3.0
      - statsforecast==1.7.4
      - statsmodels==0.14.0
      - sympy==1.12
      - tbats==1.1.3
      - tensorboard==2.2.2
      - tensorboard-data-server==0.7.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6.2.2
      - tensorflow-estimator==2.2.0
      - tensorflow-gpu==2.2.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorrt==8.6.1.post1
      - tensorrt-bindings==8.6.1
      - tensorrt-libs==8.6.1
      - termcolor==2.2.0
      - threadpoolctl==3.1.0
      - torch==2.0.1
      - torchdiffeq==0.2.4
      - torchmetrics==1.2.1
      - torchvision==0.15.2
      - triad==0.9.5
      - triton==2.0.0
      - tslearn==0.6.3
      - tune==0.1.5
      - typed-argument-parser==1.9.0
      - utilsforecast==0.1.3
      - uvicorn==0.27.1
      - uvloop==0.19.0
      - wandb==0.16.3
      - watchfiles==0.21.0
      - webencodings==0.5.1
      - websocket-client==1.3.3
      - websockets==12.0
      - werkzeug==3.0.0
      - wurlitzer==3.0.3
      - xarray==2023.1.0
      - xgboost==2.0.0
      - xyzservices==2024.4.0
      - yarl==1.9.4